version: "3.8"
services:
  fic:
    build: 
      context : ./docker_context
      dockerfile: Dockerfile-fic
    ports:
      - "8081:8080"
  storage.bucket.1:
    build: 
      context : ./docker_context
      dockerfile: Dockerfile-storage-bucket
    volumes:
      - storage.bucket.1:/bucket_storage
    environment:
      ROOT_LOCATION_PATH: /bucket_storage      
    ports:
      - "9081:8080"
  storage.bucket.2:
    build: 
      context : ./docker_context
      dockerfile: Dockerfile-storage-bucket
    volumes:
      - storage.bucket.2:/bucket_storage
    environment:
      ROOT_LOCATION_PATH: /bucket_storage      
    ports:
      - "9082:8080"
  storage.bucket.3:
    build: 
      context : ./docker_context
      dockerfile: Dockerfile-storage-bucket
    volumes:
      - storage.bucket.3:/bucket_storage
    environment:
      ROOT_LOCATION_PATH: /bucket_storage      
    ports:
      - "9083:8080"
  storage.bucket.4:
    build: 
      context : ./docker_context
      dockerfile: Dockerfile-storage-bucket
    volumes:
      - storage.bucket.4:/bucket_storage
    environment:
      ROOT_LOCATION_PATH: /bucket_storage      
    ports:
      - "9084:8080"
  storage:
    build: 
      context : ./docker_context
      dockerfile: Dockerfile-storage
    volumes:
      - .:/docker-context
    environment:
      STORAGE_BUCKET_CLIENT_CONFIG_FILE: /docker-context/storage_bucket_client_config.json
      FIC_SVC_URL: http://localhost:8081
    ports:
      - "8082:8080"
      
volumes:
  storage.bucket.1:
  storage.bucket.2:
  storage.bucket.3:
  storage.bucket.4:
